FROM node:latest as builder

WORKDIR /usr/src/app
COPY . /usr/src/app

ENV PATH="./node_modules/.bin:$PATH"

RUN yarn && yarn build

FROM nginx:latest as server

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
EXPOSE 8080